### PR TITLE
uint -> uint32_t. The project doesn't use the type 'uint'

### PR DESCRIPTION
**Pull request by tomkoen**

### CODE REVIEW

**Comment by LubosD** [comment]
I think we're casting to the type used by zlib/libbz2, aren't we?

**Comment by tomkoen** [comment]
zlib/bz2 use another type "uInt". I don't think it's cool to have so many variants of unsigned integer.

**Comment by tomkoen** [comment]
int is never 64-bit

**Comment by jief666** [comment]
"never" **IS** an assumption. They tend to be proved wrong, one day.
Doesn't harm to be 100% safe instead of coincidentally safe.

**Pull request merged**
