### PR TITLE
readme update related to lzfse

### PR DESCRIPTION
**Pull request by tomkoen**
FYI: the status picture from TeamCity doesn't work for quite a while

### CODE REVIEW

**Comment by jief666** [comment]
@tomkoen : here is my first version that integrate HFS & APFS disk images, encrypted or clear, sparsebundle or plain files.
I didn't test every single possibility (APF or HSF, encrypted or clear, different compression or not, GPT or Apple map or no map make quite a lot of possibilities), but I checked quite a few.
It's a work in progress branch. There is some cleaning, duplicates...

@LubosD @bugaevc : I can do some pull request if you are interested by some features (encryption, sparsebundle, etc.). Just let me know.

**Comment by LubosD** [comment]
@jief666 You sure this comment belongs here?

**Comment by jief666** [comment]
Sure, no, not really. I opened an issue on my own project. I don't know if you get notified when I do that.

**Comment by kleuter** [comment]
@jief666 

> I don't know if you get notified when I do that.

nope

**Comment by tomkoen** [comment]
@jief666 

> I don't know if you get notified when I do that.

nope

**Comment by jief666** [comment]
So I'll hijack this one last time this thread to say that, if darling-dmg people are interested by new features from my project : https://github.com/jief666/hdimount/tree/wip, that's no problem. I'll do the pull request of features you'd like.
If we want to talk about this, we can do it here : https://github.com/jief666/hdimount/issues/1.

**Pull request closed without merging**
