### PR TITLE
Check m_descriptorData size in initFromBuffer()

### PR DESCRIPTION
**Pull request by jief666**

### CODE REVIEW

**Comment by jief666** [comment]
Not in case of the copy constructor, is it ?
Copy constructor call operator = that doesn't initialise them. Am I right ?

As a general principle, not taking into account the caller context makes it more reliable.

**Comment by LubosD** [comment]
@jief666 It'd be better to do the null initialization inside `HFSBTreeNode(const HFSBTreeNode& that)`, then you don't ever need to do it in `initFromBuffer()`.

To put it differently, either keep it in `initFromBuffer()` and remove it from all constructors or only do it in constructors.

**Comment by jief666** [comment]
What about this ?
I separated the job : ctors take care if data (m_descriptorData), initFromBuffer take of of convenience pointer derived from data.

**Comment by jief666** [comment]
@LubosD, I resolved the conflicts.
Note : default ctor, copy ctor and assignment operator are not used in darling-dmg. I didn't remove them is case they are use in darling. I would if you tell me it's ok to remove them.

**Comment by jief666** [comment]
Also took the occasion to remove one unused method in HFSCatalogBTree.cpp, and to make findLeafNode returning nullptr instead of an empty/invalid HFSBTreeNode.

**Comment by jief666** [comment]
Good, thanks.

**Pull request merged**
